config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  resources :cities
  resources :users
  resources :gossips
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user

	validates :title,
		presence: true,
		length: { in: 3..14 }

	validates :content,
		presence: true
end

app/models/user.rb
class User < ApplicationRecord
	belongs_to :city
	has_many :gossips
	has_secure_password
	validates :password,
		presence: true,
		length: {minimum: 6}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	add_flash_types :success, :danger, :error, :info, :warning

	include SessionsHelper
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def index
    @city = City.all
  end

  def show
    @gossips = Gossip.all
    @city = City.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  before_action :authenticate_user, only: [:show]

  def index
  	@gossips = Gossip.all
  end

  def new
    @gossip = Gossip.new
  end

  def create
#    @city = City.create(name: params[:city_name])
 # 	@user = User.create(first_name: params[:gossip_user], city_id: @city.id)
    
    @gossip = Gossip.create(content: params[:gossip_content], title: params[:gossip_title])
      @gossip.user = User.find_by(id: session[:user_id])
  		if @gossip.save
  			redirect_to gossips_path
        flash[:success] = "Gossip is validate !" 
  		else
        flash[:danger] = "Invalid title or content."
  			render :new
  		end
  end

  def show
    @gossip = Gossip.find(params[:id])
  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(post_params)
      redirect_to @gossip
      flash[:success] = "The gossips has been update succefully."
    else
      flash[:danger] = "An error has happened, try again."
      render :edit
      end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to gossips_path
  end

  def post_params
    params.require(:gossip).permit(:title, :content)
  end
end

  def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	
  end

  def create
  	user = User.find_by(email: params[:session][:email])
 		if user && user.authenticate(params[:session][:password])
 			session[:user_id] = user.id
 			redirect_to user_path(user.id)
 			flash[:success] = 'Tu es bien connecté.'
 		else
 			flash[:danger] = 'Invalid email/password combination'
 			render :new
 		end
  end

  def destroy
  	session.delete(:user_id)
  	redirect_to gossips_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/create.html.erb
<h1>Cities#create</h1>
<p>Find me in app/views/cities/create.html.erb</p>

app/views/cities/destroy.html.erb
<h1>Cities#destroy</h1>
<p>Find me in app/views/cities/destroy.html.erb</p>

app/views/cities/edit.html.erb
<h1>Cities#edit</h1>
<p>Find me in app/views/cities/edit.html.erb</p>

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/new.html.erb
<h1>Cities#new</h1>
<p>Find me in app/views/cities/new.html.erb</p>

app/views/cities/show.html.erb
<h1> <%= @city.name %> </h1>
<br />
<p>Gossips liés à la ville:</p>

<p><% @gossips.select{ |gossip_same_city|  (gossip_same_city.user.city_id == @city.id)  }.each do |gossip| %>
	De: <%= link_to "#{gossip.user.first_name}", user_path(gossip.user.id) %> <br />
	Titre: <%= link_to "#{gossip.title}", gossip_path(gossip.id) %> <br /> <br />
	<% end %>
</p>

app/views/cities/update.html.erb
<h1>Cities#update</h1>
<p>Find me in app/views/cities/update.html.erb</p>

app/views/gossips/edit.html.erb
<h1>Editer le gossip: <br /> <%= @gossip.title %></h1>
<br />
<div class="container">
	<%= form_for @gossip do |f| %>
		<div class="form-group">
			<label>Titre du gossip</label>
			<%= f.text_field :title, class: 'form-control' %>
		</div>

		<div class="form-group">
			<label>Contenu du gossip</label>
			<%= f.text_area :content, class: 'form-control' %>
		</div>

		<div class="form-group">
		<button type="submit" class="btn btn-primary">Modifier le gossip</button>
	</div>
	<% end %>
</div>

app/views/gossips/index.html.erb
<h1>The gossip project</h1>
	<p> Tu veux creer un potin?
	<a <%= link_to "Clique ici", new_gossip_path %> </a></p>


	<p> <% @gossips.each do |gossip| %>
		
De : <%= link_to "#{gossip.user.first_name}", user_path(gossip.user.id) %>, <%= link_to "#{gossip.title}", gossip_path(gossip.id) %> <br />
<% end %></p>

app/views/gossips/new.html.erb
<h1> Création d'un nouveau gossip</h1>

<div class="container">
	<form action= <%= gossips_path %> method="POST">
		<div class="form-group">
			<input type="hidden" name="authenticity_token" value= <%= form_authenticity_token %> >
		</div>

		<div class="form-group">
			<label> Le titre de ton gossip: </label><br />
			<input type="text" name="gossip_title"> <br />
		</div>

		<div class="form-group">
			<label> Votre gossip: </label><br />
			<input type="text" name="gossip_content"> <br />
		</div>
		<br />
			<input type="submit" value="Valider">
		
	</form> 
</div>

app/views/gossips/show.html.erb
<h1> <%= @gossip.title %> </h1>

<p> Auteur: <%= link_to "#{@gossip.user.first_name} #{@gossip.user.last_name}", user_path(@gossip.user.id) %> <br />
Venant de <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %></p>


<p> <%= @gossip.content %> </p>

<p>Le gossip vous semble incorrect? Modifier le <%= link_to "Ici", edit_gossip_path(@gossip.id) %> ! </p>

<%= link_to "Supprimer le gossip", @gossip,  method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Gossippro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= gossips_path %>">Gossips</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
         <% if current_user == nil %> <%= link_to "Connexion", new_session_path, :class => "btn btn-primary" %> 
         <% else %>
       <%= link_to "Deconnecter", session_path(session.id), method: :delete, :class => "btn btn-primary" %>
       <% end %>
    </form>


  </div>
</nav>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= name %>'>
            <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1> <%= @user.first_name %> <%= @user.last_name %> </h1>
<p>Prénom: <%= @user.first_name %> <br />
	Nom: <%= @user.last_name %> <br />
	Age: <%= @user.age %> ans<br />
	Email: <%= @user.email %><br />
	Ville: <%= link_to "#{@user.city.name}", city_path(@user.city.id) %> <br />
</p> 

<p>Description: <br /><%= @user.description %></p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>